### ISSUE TITLE
Support "run on ready"

### ISSUE THREAD

**Issue by tjconcept** [Hilzu/chokidar-cmd#2]
Add a command line option to run the command once chokidar emits it's ready event.

**Comment by tjconcept** [comment]
Context: I am using this package as a replacement of nodemon in something along the lines of what Keith describes here: http://blog.keithcirkel.co.uk/how-to-use-npm-as-a-build-tool/ (https://twitter.com/tjconceptdk/status/581400775802392576).

**Comment by Hilzu** [comment]
This seems like a sensible option to add. I'll probably implement this during the weekend. That blog post by Keith also inspired me to make this package so that I could put all my build stuff to package.json scripts field.

**Comment by tjconcept** [comment]
Awesome!

**Comment by tjconcept** [comment]
You're a hero :+1:
