### ISSUE TITLE
chokidar-cmd cannot run "npm" on windows

### ISSUE THREAD

**Issue by Pomax** [Hilzu/chokidar-cmd#4]
There is a lovely quirk around Node for windows that causes npm scripts that involve chokidar like the following to not work on windows:

```
  ...
  "scripts": {
    ...
    "start:less": "chokidar-cmd -c 'npm run less' -t less",
    ...
  },
  ...
```

[The reason for this](http://stackoverflow.com/questions/17516772/using-nodejss-spawn-causes-unknown-option-and-error-spawn-enoent-err) is that on windows, the `npm` command only works because it lets windows autoresolve it from the non-existent `npm.exe` to `npm.cmd` - however, when Node's `exec` or `spawn` are used, that resolution does not happen, and so calls like `npm run less` will fail unless they are specifically rewritten to (1) use `spawn` rather than `exec` and (2) use `npm.cmd` instead.

While a very specific problem, having chokidar trigger npm scripts, because it's a node utility, seems high incident enough to warrant checking what the operational call is, and if it's "npm", rewrite it to "npm.cmd" when `process.platform === "win32"` (which, sadly, but usefully, covers both 32 and 64 bit versions of windows)

**Comment by Hilzu** [comment]
I agree that this problem warrants a look. I'll fix this on Sunday/Monday when I get by a computer.

**Comment by Pomax** [comment]
awesome, thanks!

**Comment by Hilzu** [comment]
I'm unable to reproduce this problem on Windows 10, Node.js 6.5.0 and npm 3.10.3. The default installation adds `C:\Program Files\nodejs\` to path and it contains an executable named `npm` so it should work as it is. I wrote a [test case](https://github.com/Hilzu/chokidar-cmd/blob/master/test.js#L74) for this and was also unable to reproduce it in [AppVeyor](https://ci.appveyor.com/project/Hilzu/chokidar-cmd/build/1.0.5). What version of Windows, Node and npm did you encounter this problem with?

**Comment by Pomax** [comment]
Maybe I'm missing something, but https://github.com/Hilzu/chokidar-cmd/blob/master/test.js#L109 does not look like it invokes the actual CLI tool, but instead calls the js script, which means it'll be doing something different from a real run, with a different runtime environment, no?

I'm using Win10 x64 pro, with node 6.2.2 / npm 3.9.5, and the standard `cmd` shell (not powershell or a cygwin/msys bash) on our https://github.com/mozilla/learning.mozilla.org/ repo, with https://github.com/mozilla/learning.mozilla.org/blob/master/package.json#L35 breaking for us. Chokidar will start listening:

```
C:\...> npm run start:less

> chokidar-cmd -c 'npm run less' -t less

[chokidar-cmd] Watching "less" and running command "'npm" on changes
```

But then when a file is modified, it errors out:

```
''npm' is not recognized as an internal or external command,
operable program or batch file.
[chokidar-cmd] ERROR: { Error: Command failed: 'npm
''npm' is not recognized as an internal or external command,
operable program or batch file.

    at ChildProcess.exithandler (child_process.js:207:12)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:852:16)
    at Socket.<anonymous> (internal/child_process.js:323:11)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at Pipe._handle.close [as _onclose] (net.js:492:12) killed: false, code: 1, signal: null, cmd: '\'npm' }
```

Works fine on OSX and other 'nix flavours, but breaks on Windows.

**Comment by Pomax** [comment]
How I'm reproducing this consistently:
1. new test dir with a `package.json` and a dir called `lookatme`
2. `package.json` with the following content:

```
{
  "name": "_",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "chokidar-cmd -c 'npm run test:2' -t lookatme",
    "test:2": "echo 'hurray'"
  },
  "keywords": [],
  "author": "",
  "license": "ISC",
  "dependencies": {
    "chokidar": "^1.6.0",
    "chokidar-cmd": "^1.2.1"
  }
}
```

Then to see the effect, run `npm i` to install chokidar/chokidar-cmd, and run `npm test` to start the watch task. 

```
c:\Users\Pomax\Documents\git\temp\_>npm run test

> _@1.0.0 test c:\Users\Pomax\Documents\git\temp\_
> chokidar-cmd -c 'npm run test:2' -t lookatme

[chokidar-cmd] Watching "lookatme" and running command "'npm" on changes
```

Creating a file in the `lookatme` dir triggers chokidar's watching, it tries to run its instruction, and errors on it; the easiest way I can think of is to just run a `touch lookatme/whatever` so that a file gets created.

```
''npm' is not recognized as an internal or external command,
operable program or batch file.
[chokidar-cmd] ERROR: { Error: Command failed: 'npm
''npm' is not recognized as an internal or external command,
operable program or batch file.

    at ChildProcess.exithandler (child_process.js:207:12)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:852:16)
    at Socket.<anonymous> (internal/child_process.js:323:11)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at Pipe._handle.close [as _onclose] (net.js:492:12) killed: false, code: 1, signal: null, cmd: '\'npm' }
```

Which makes sense: there is no `C:\Program Files\Nodejs\npm.exe` for windows to run.

While there _is_ a file called `C:\Program Files\Nodejs\npm`, that's a bash shell script, and Windows has no idea how to run those natively; it only knows how to run `.exe` files, and how to interpret `.bat` and `.cmd` scripts.

Luckily, there is a `C:\Program Files\Nodejs\npm.cmd` as well, which windows will happily run when you call `npm` as a native command through window's executable resolution, but it won't automatically do that when a call happens through an exec API like Node's `child_process.exec()` or `child_process.spawn()`.

**Comment by Pomax** [comment]
If I take off the quotes around the task that `chokidar-cmd` needs to run, so using `"test": "chokidar-cmd -c npm run test:2 -t lookatme",`, chokidar-cmd does succeed in calling `npm`, but does it... wrong?

```
[chokidar-cmd] Watching "lookatme" and running command "npm" on changes
```

and then when a file changes:

```
Usage: npm <command>

where <command> is one of:
    access, adduser, bin, bugs, c, cache, completion, config,
    ddp, dedupe, deprecate, dist-tag, docs, edit, explore, get,
    help, help-search, i, init, install, install-test, it, link,
    list, ln, logout, ls, outdated, owner, pack, ping, prefix,
    prune, publish, rb, rebuild, repo, restart, root, run,
    run-script, s, se, search, set, shrinkwrap, star, stars,
    start, stop, t, tag, team, test, tst, un, uninstall,
    unpublish, unstar, up, update, v, version, view, whoami

npm <cmd> -h     quick help on <cmd>
npm -l           display full usage info
npm help <term>  search for help on <term>
npm help npm     involved overview

Specify configs in the ini-formatted file:
    C:\Users\Mike\.npmrc
or on the command line via: npm <command> --key value
Config info can be viewed via: npm help config

npm@3.9.5 C:\Program Files\nodejs\node_modules\npm
[chokidar-cmd] ERROR: { Error: Command failed: npm

    at ChildProcess.exithandler (child_process.js:207:12)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:852:16)
    at Socket.<anonymous> (internal/child_process.js:323:11)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at Pipe._handle.close [as _onclose] (net.js:492:12) killed: false, code: 1, signal: null, cmd: 'npm' }
```

We're using the quotes to ensure that the command that gets run is contained, so maybe there are two problems: 
1. `chokidar-cmd -c 'some task'` seems to try to run `'some` (with quote) instead of the entire command inside the quotes, with the quotes stripped off, and 
2. when quotes are not used, `chokidar-cmd -c npm run something` only runs `npm`, not `npm run something`, somehow ignoring everything after the original command?

**Comment by Pomax** [comment]
Well then... found it. Quoting the full run command _does_ work, but _only_ if double quotes are used, which is probably worth extending to both single and double quotes.

This works: `"chokidar-cmd -c \"npm run test:2\" -t lookatme"`
This calls `'npm`, which isn't an executable: `"chokidar-cmd -c 'npm run test:2' -t lookatme"`
This calls `npm` only (which makes sense): `"chokidar-cmd -c npm run test:2 -t lookatme"`

I'll close this bug and file a new one to add support for single quote command wrapping in addition to double quote command wrapping.

**Comment by Hilzu** [comment]
Just a note: you shouldn't have to add chokidar to dependencies explicitly when using chokidar-cmd.

**Comment by Pomax** [comment]
good to know, thank!

**Comment by javalight** [comment]
Summary: For windows use `\"` not `'` 🥳
