### ISSUE TITLE
wrapping watch commands in single quotes runs as if the quotes themselves are plain string content

### ISSUE THREAD

**Issue by Pomax** [Hilzu/chokidar-cmd#5]
Based on https://github.com/Hilzu/chokidar-cmd/issues/4, the following two cases behave predictably:
1. `chokidar-cmd -c "npm run test:2" -t somedir` - runs `npm run test:2` on changes
2. `chokidar-cmd -c npm run test:2 -t somedir` - runs `npm` on changes

However, single quotes behave counter-intuitively: `chokidar-cmd -c 'npm run test:2' -t somedir`, while expected to run the same `npm run test:2` as in (1), instead runs `'npm` as in (2).

It would be a good idea to make `chokidar-cmd` treat both double and single quotes as command wrappers, so that when quoted, irrespective of the quote symbols, the full command gets run.

**Comment by Hilzu** [comment]
npm scripts are run directly in the OS shell which in Windows is cmd. It doesn't support quoting with single quotes so double quotes should always be used when writing cross platform npm scripts. The readme does contain this gotcha and I'll update it to use double quotes.  I don't think chokidar-cmd should be trying to hide the differences between shell syntaxes.

**Comment by Pomax** [comment]
Hm, the best solution to a gotcha is highlighting it when and where it happens, rather than only mentioning it a README, so it feels like it's worth making `chokidar-cmd` warn about that when it sees it:

```
[chokidar-cmd] Warning: command to run contains a single quote.
If you meant to wrap a complex command in quotes, please use
double quotes, or you can add the -nw flag to the chokidar-cmd
call to suppress this warning.
```

And then it can run as normal, while warning the user about bad quoting habits, as well as giving power users who actually need to run an executable starting with a single quote a way to suppress the warning. (_do those even exist? I doubt they do, this feels like a super clear user-error where a call starting with a quote should have been a double quote 100% of the time_)

**Comment by Pomax** [comment]
Sorry, was there a reason to just close this? It's still a problem in 2018 (I even ran into it last week). Almost no one knows about the difference between " working in windows and ' completely breaking, so warning people on linux/unix/osx/etc that they've written a command that is cross-platform incompatible (the opposite reason they're even using chokidar at all) would still be quite good.

(unless that is still going to happen in #4?)

**Comment by thomasfl** [comment]
I have implemented this excact functionality in my own cli written in ruby https://github.com/thomasfl/filewatcher It is very useful. I guess you could set ut some automated tests that would run in jenkins or something similar, that can execute in different os’es.

**Comment by Hilzu** [comment]
I’ve decided to deprecate this package in favor of chokidar-cli that’s way more popular than this and recommended in the chokidar readme.

**Comment by Pomax** [comment]
fair enough, and props to you on that decision, I've had a few packages that I should have deprecated well before when I actually did >_>
