### ISSUE TITLE
Make the first command line argument the file globs and the second argument the command string

### ISSUE THREAD

**Issue by thomasfl** [Hilzu/chokidar-cmd#7]
There's not much use running chokidar-cmd without a file-or-dir-or-glob and a command. Instead of having -c and -t options, the first command line argument could be a list of file-or-dir-or-glob the second command line option could be the command to run. 

For example, instead of typing this:

```
  chokidar-cmd -c "npm run less" -t src/styles.less -t vender/styles.less
```

Users would instead type the shorter:

```
  chokidar-cmd "src/styles.less vendor/styles.less" "npm run less"
```

This would make chokidar-cmd a javascript replacement for my rubygem https://github.com/thomasfl/filewatcher

**Comment by Hilzu** [comment]
The `-t` argument can be specified several times so changing it to a positional argument is not that easy. Not sure if I like passing several files as a space separated string. Is that style common in other CLI tools?

Changing the CLI API radically would be an breaking change and requires a major version update which I am a bit hesitant to do without good reasons.

**Comment by thomasfl** [comment]
It's how it's done in filewatcher https://github.com/thomasfl/filewatcher You can take a quick look at the examples, or try downloading it.

To be exact, the last command line argument is the command string and the rest is considered filenames (or dir's or globs). Command line options is stripped out first. So this means you can actually do ut like this without escaping:

```
    chokidar-cmd *.js *.json ./run_tests
```

There's actually is a style guide from [IEEE](http://pubs.opengroup.org/onlinepubs/9699919799/basedefs/V1_chap12.html) on how to create command line utilities with switches and operands and document them. 

The main pattern is like this:
```
    utility_name[-a][-b][-c option_argument]
        [-d|-e][-f[option_argument]][operand...]
```

The ...operand means zero or more operands can be specified

Escaping with " or ' is only not necessary when running a single command with no arguments, like this

```
    chokidar-cmd *.js ./run_tests
```

Escaping makes it possible to let javascript do the file globbing instead of the OS.

```
    chokidar-cmd '**/*.js testdata/*.json' ./run_tests
```

I usually prefer to clear the screen between each test run, like this. So then I need to escape the command string:

```
    chokidar-cmd '**/*.js' 'clear && ./run_tests
```

It is possible to make this change backwards compatible by both supporting the -t and -c switches and the new API.
